[package]
name = "ringo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
rand = "0.8.5"
diesel = { version = "2.1.4", features = ["postgres"] }
dotenvy = "0.15.7"